version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    image: frontend:moviebase_react
    container_name: moviebase_react_container
    command: npm start
    depends_on:
      - db
      - backend
  backend:
    build: ./backend
    ports:
      - 8000:8000
    image: backend:moviebase_django
    container_name: moviebase_django_container
    command: > 
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata initial_data.json &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=moviebase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db